# Generated by Django 4.2.5 on 2024-02-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=10)),
                ('Coordinate', models.CharField(max_length=40)),
                ('Temperature', models.CharField(max_length=40)),
                ('Pressure', models.CharField(max_length=40)),
                ('Humidity', models.CharField(max_length=40)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
